##config
---
context: "/"
group: study
project: apt-management
development:
  comm:
    nodePort: 3000
  mqtt:
    protocol: "mqtt"
    host: "mqtt-dashboard.com"
    topic: "sadang/data"
  api:
    openweathermap: e402fac442675f72e35dff845ffc4e09
  db:
    username: "rkdden"
    password: "1234"
    database: "aptmanagement"
    host: "127.0.0.1"
    dialect: "mysql"
    timezone: "+09:00"
production:
  comm:
    nodePort: 3000
  mqtt:
    protocol: "mqtt"
    host: "mqtt-dashboard.com"
    topic: "sadang/data"
  api:
    openweathermap: e402fac442675f72e35dff845ffc4e09
  db:
    username: "root"
    password: "데이터베이스 비밀번호"
    database: "aptmanagement"
    host: "127.0.0.1"
    dialect: "mysql"
    timezone: "+09:00"
