##config
---
context: "/"
group: study
project: apt-management
development:
  comm:
    nodePort: 3000
  mqtt:
    protocol: "mqtt"
    host: "mqtt-dashboard.com"
    topic: "sadang/data"
    # 데이터베이스
  db:
    username: "root"
    password: "디비 비밀번호"
    database: "aptmanagement"
    host: "127.0.0.1"
    dialect: "mysql"
    timezone: "+09:00"
production:
  comm:
    nodePort: 3000
  mqtt:
    protocol: "mqtt"
    host: "mqtt-dashboard.com"
    topic: "sadang/data"
    # 데이터베이스
  db:
    username: "root"
    password: "데이터베이스 비밀번호"
    database: "aptmanagement"
    host: "127.0.0.1"
    dialect: "mysql"
    timezone: "+09:00"
