##config
---
context: "/"
group: study
project: apt-management
development:
  comm:
    nodePort: 3000
  mqtt:
    protocol: "mqtt"
    host: "mqtt-dashboard.com"
    topic: "sadang/data"
  db: 
    database: "aptManagement"
    username: "root"
    password: "1210"
    host: "127.0.0.1"
    timezone: "+09:00"
    dialect: "mysql"
production:
  comm:
    nodePort: 3000
  mqtt:
    protocol: "mqtt"
    host: "mqtt-dashboard.com"
    topic: "sadang/data"
  
